name: Publish Wiki

on:
  push:
    paths:
      - .github/wiki/**
    branches:
      - develop

jobs:
  publish:
    name: Publish Wiki
    uses: nimblehq/publish-github-wiki-action@0.0.1-alpha
    with:
      USER_NAME: Terone
      USER_EMAIL: 34730459+bterone@users.noreply.github.com
    secrets:
      USER_TOKEN: ${{ secrets.GH_TOKEN }}
