name: Publish Wiki

on:
  push:
    paths:
      - .github/wiki/**
    branches:
      - develop

jobs:
  publish:
    name: Publish Github Wiki

    runs-on: ubuntu-latest

    timeout-minutes: 1

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Publish Wiki
        uses: nimblehq/publish-github-wiki-action@v0.0.5-alpha
        env:
          USER_NAME: Terone
          USER_EMAIL: 34730459+bterone@users.noreply.github.com
          USER_TOKEN: ${{ secrets.GH_TOKEN }}
