name: Publish Wiki

on:
  push:
    branches:
      - chore/github-wiki

jobs:
  publish:
    name: Publish Github Wiki

    runs-on: ubuntu-latest

    timeout-minutes: 1

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Publish Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          WIKI_DIR: .github/wiki
          GH_NAME: Terone
          GH_MAIL: 34730459+bterone@users.noreply.github.com
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
